name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
        exclude:
          - os: ubuntu-latest
            node_version: 6
      #fail-fast: true
      max-parallel: 3
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          #node-version: '10.x'
          node-version: ${{ matrix.node_version }}
      - name: Log node version v2
        run: node -v
