name: Container
on: workflow_dispatch

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.11
      #env: 
      #ports:
      #volumes:
      #options: --cpus 1 --host
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release

