name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app: 
        image: alialaa17/node-api:latest
        ports:
          - 3001:3000
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
      #env: 
      #volumes:
      #options: --cpus 1 --host
    steps:
      - name: Post a user from VM
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"dweded\"}'"
      - name: Get users
        run: "curl -X GET http://localhost:3001/api/users"
