name: Actions Workflow

#on: [push, pull_request]
on:
  schedule:
    - cron: "*/5 * * * *"
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-22.04
    steps:
      - name: List Files
        run: |
          pwd
          ls
          echo "GITHUB_SHA (COMMIT ID) := $GITHUB_SHA"
          echo "GITHUB_REPOSITORY (COMMIT ID) := $GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE (COMMIT ID) := $GITHUB_WORKSPACE"
          echo "github.token := ${{ github.token }}"

          echo "You can use this values with e.g.:"
          echo "git clone git@github:\$GITHUB_REPOSITORY"
          echo "git checkout \$GITHUB_SHA"
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files v2
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        #uses: actions/hello-world-javascript-action@master
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting TIme
        run: echo "${{ steps.greet.outputs.time }}"
