name: Shell Commands

on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - v1.*

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps:
      - name: echo a string
        run: echo "Hello GitHub Actions!"
      - name: multiline scripts
        run: |
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-2022
    needs: ["run-shell-command"]
    steps:
    - name:  PWD PowerShell default
      run: Get-Location
    - name: PWD win BASH
      run: pwd
      shell: bash
